Repository mathleite/marvel-application-backend, pull requests merged in 2019-10, with the labels that each got.

#3 Create Marvel Controller and Marvel Route
  integrator/app/Http/Controllers/MarvelController.php
  integrator/routes/api.php
Labels: SPRINT 1, enhancement, priority: high

#5 Integrate frontend Communication
  integrator/.env.example
  integrator/app/Http/Controllers/MarvelController.php
  integrator/routes/api.php
Labels: SPRINT 2, enhancement, priority: high

#4 Marvel Api connection
  integrator/.env.example
  integrator/app/Base/Interfaces/BaseHttpClientServiceInterface.php
  integrator/app/GuzzleHttpClient/Service/GuzzleHttpClientService.php
  integrator/app/Providers/AppServiceProvider.php
  integrator/composer.json
  integrator/composer.lock
Labels: SPRINT 2, enhancement, priority: normal

#6 Create GetAll Characters and improve GuzzleHttpClientService
  integrator/app/Base/Interfaces/BaseHttpClientServiceInterface.php
  integrator/app/Characters/controllers/CharactersController.php
  integrator/app/Characters/resources/CharactersResource.php
  integrator/app/Characters/services/CharactersDoCorrectRequestByControllerService.php
  integrator/app/GuzzleHttpClient/Service/GuzzleHttpClientService.php
  integrator/app/Http/Controllers/MarvelController.php
  integrator/app/Providers/AppServiceProvider.php
  integrator/config/app.php
  integrator/routes/api.php
Labels: SPRINT 3, enhancement, priority: high
